#!/usr/bin/env python3
"""Generate the symbology pattern tables as assembly source.

Run once and commit the output; it is checked in as readable assembly so
the decoder builds with nothing but an assembler.  Re-run it only if a
table changes:

    python3 barcode/tools/gen_tables.py

Code 39 data comes from `analysis/micronic/barcode.py`, which is exercised
by `analysis/test_barcode.py` against the firmware.  UPC data is built here
from the L-code bit patterns and *checked* rather than trusted: every
pattern must be seven modules in exactly four runs with odd parity, which
is what makes it a valid UPC left-hand code.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT / "analysis"))
from micronic.barcode import CODE39_PATTERNS          # noqa: E402
sys.path.insert(0, str(ROOT / "barcode" / "tools"))
from upc import PARITY, UPCE_PARITY                   # noqa: E402

SRC = ROOT / "barcode" / "src"

# UPC/EAN left-hand ("L") codes, seven modules each, LSB last.  The right-hand
# codes are the bitwise complement and so have the SAME run lengths, which is
# why one table decodes both halves.
UPC_L = {
    0: "0001101", 1: "0011001", 2: "0010011", 3: "0111101", 4: "0100011",
    5: "0110001", 6: "0101111", 7: "0111011", 8: "0110111", 9: "0001011",
}


def runs(bits):
    """Run lengths of a module string, e.g. '0001101' -> [3, 2, 1, 1]."""
    out, last, n = [], bits[0], 0
    for b in bits:
        if b == last:
            n += 1
        else:
            out.append(n)
            last, n = b, 1
    out.append(n)
    return out


def code39_table():
    lines = [
        ";; Code 39 -- generated by tools/gen_tables.py, do not hand-edit.",
        ";;",
        ";; One entry per character: a 9-bit pattern and its ASCII code.",
        ";; The pattern bit for each element is 1 when the element is wide.",
        ";; Bit 8 is the first element (a bar); elements alternate bar/space.",
        ";; Exactly three of the nine elements are wide in every character.",
        "",
        "c39_count:  defb %d" % len(CODE39_PATTERNS),
        "c39_table:",
    ]
    for ch, pat in CODE39_PATTERNS.items():
        assert len(pat) == 9, ch
        assert pat.count("W") == 3, ("Code 39 needs exactly 3 wide", ch, pat)
        key = int("".join("1" if c == "W" else "0" for c in pat), 2)
        name = {" ": "space", "$": "dollar", "/": "slash", "+": "plus",
                "%": "percent", "-": "dash", ".": "dot", "*": "start/stop"}.get(ch, ch)
        # One directive per entry -- `defw x : defb y` needs ':' as a
        # statement separator, which z88dk accepts and pasmo does not.
        lines.append("    defb $%02X,$%02X,%-5s ; %-9s %s"
                     % (key & 0xFF, key >> 8,
                        "'%s'" % ch if ch not in "'" else "39", pat, name))
    return "\n".join(lines) + "\n"


def upc_table():
    # The decoder tells an L code from a G code by looking a quad up as it
    # stands and then reversed.  That only works if no L pattern is another
    # L pattern reversed -- otherwise a digit would decode two ways and the
    # parity, and with it EAN-13's thirteenth digit, would be ambiguous.
    packed = {}
    for d in range(10):
        r = runs(UPC_L[d])
        packed[d] = sum((w - 1) << (6 - 2 * i) for i, w in enumerate(r))
    forward = set(packed.values())
    reversed_ = {sum((w - 1) << (6 - 2 * i)
                     for i, w in enumerate(reversed(runs(UPC_L[d]))))
                 for d in range(10)}
    assert not (forward & reversed_), (
        "an L pattern equals another reversed; L and G would be ambiguous",
        sorted(forward & reversed_))


    lines = [
        ";; UPC-A / EAN -- generated by tools/gen_tables.py, do not hand-edit.",
        ";;",
        ";; Each digit is four elements spanning seven modules.  A run length",
        ";; is 1..4, so it fits in two bits; the four are packed into one byte,",
        ";; first element in the high pair.  The right-hand codes are the",
        ";; bitwise complement of the left and therefore have identical run",
        ";; lengths, so this one table decodes both halves of the symbol.",
        "",
        "upc_table:",
    ]
    for d in range(10):
        bits = UPC_L[d]
        r = runs(bits)
        assert len(bits) == 7, d
        assert len(r) == 4, ("a UPC digit is four runs", d, r)
        assert sum(r) == 7, ("a UPC digit spans seven modules", d, r)
        assert bits.count("1") % 2 == 1, ("L-codes have odd parity", d, bits)
        packed = 0
        for w in r:
            packed = (packed << 2) | (w - 1)
        lines.append("    defb $%02X          ; %d  %s  widths %s"
                     % (packed, d, bits, "".join(str(x) for x in r)))
    return "\n".join(lines) + "\n"


def ean_parity_table():
    lines = [
        ";; EAN-13 leading digit -- generated by tools/gen_tables.py.",
        ";;",
        ";; The thirteenth digit is not drawn anywhere in the symbol.  It is",
        ";; recorded only in *which* of the six left-hand digits use the",
        ";; even-parity G code instead of the odd-parity L code.  One bit per",
        ";; left-hand digit, first digit in bit 5, G = 1.",
        ";;",
        ";; A pattern that is not in this table is not an EAN-13.",
        "",
        "ean_parity:",
    ]
    for d in range(10):
        pat = PARITY[d]
        assert len(pat) == 6, d
        assert pat[0] == "L", ("the first left digit is always L", d, pat)
        assert pat.count("G") == (0 if d == 0 else 3), \
            ("every leading digit but zero uses three G codes", d, pat)
        key = int("".join("1" if c == "G" else "0" for c in pat), 2)
        lines.append("    defb $%02X          ; %d  %s" % (key, d, pat))
    return "\n".join(lines) + "\n"


def upce_parity_table():
    lines = [
        ";; UPC-E parity -- generated by tools/gen_tables.py.",
        ";;",
        ";; UPC-E draws neither its number system nor its check digit.  Both",
        ";; live in which of the six digits use the even-parity G code.  One",
        ";; bit per digit, first digit in bit 5, G (even) = 1.",
        ";;",
        ";; These ten are number system 0, indexed by check digit.  Number",
        ";; system 1 is the same set complemented in six bits, so the decoder",
        ";; tries the pattern as it stands and then XOR 3Fh, rather than",
        ";; carrying a second table.",
        "",
        "upce_parity:",
    ]
    seen = set()
    for c in range(10):
        pat = UPCE_PARITY[c]
        assert len(pat) == 6, c
        assert pat.count("E") == 3, ("every UPC-E parity uses three G codes", c, pat)
        key = int("".join("1" if ch == "E" else "0" for ch in pat), 2)
        assert key not in seen and (key ^ 0x3F) not in seen, \
            ("a pattern must not collide with another, or another's "
             "complement -- that is what makes the number system recoverable",
             c, pat)
        seen.add(key)
        lines.append("    defb $%02X          ; check %d  %s" % (key, c, pat))
    return "\n".join(lines) + "\n"


def main():
    (SRC / "upce_parity.inc").write_text(upce_parity_table())
    (SRC / "ean_parity.inc").write_text(ean_parity_table())
    (SRC / "code39_table.inc").write_text(code39_table())
    (SRC / "upc_table.inc").write_text(upc_table())
    print("wrote src/code39_table.inc, src/upc_table.inc,\n           src/ean_parity.inc, src/upce_parity.inc")
    print("  Code 39: %d characters" % len(CODE39_PATTERNS))
    print("  UPC:     10 digits, L and G patterns provably disjoint")
    print("  EAN-13:  10 parity patterns, all self-checks passed")
    print("  UPC-E:   10 parity patterns, no collisions with complements")


if __name__ == "__main__":
    main()
